### ISSUE TITLE
Release version 2.0

### ISSUE THREAD

**Issue by AlekseyMartynov** [DevExpress/DevExtreme.AspNet.Data#276]
- [x] Don't use fields in public API (#231 in particular)
- [x] Target NET 4.5.2 ([reference](https://community.devexpress.com/blogs/ctodx/archive/2018/07/11/devexpress-universal-visual-studio-net-and-c-support-going-forward.aspx)) and NET Standard 2.0, drop NET40.cs shims
- [x] EF Core remote grouping (#181, wait for official 2.2.0?)
- [x] No need to [test against DevExtreme < 18.1](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/1f09ecdec373c520f0a93b31fc3b4a9a2693eaa5/appveyor.yml#L25-L28), raise `devextreme` dependency in package.json
- [x] No need to [test in IE < 11](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/1f09ecdec373c520f0a93b31fc3b4a9a2693eaa5/js-test/karma.conf.js#L19)
- [x] Publish currently hidden `RemoteSelect`, `PreSelect`, add docs
- [x] Make `DataSourceLoadOptionsBase` non abstract
- [x] Switch to ESLint (#279)

**Comment by AlekseyMartynov** [comment]
https://www.nuget.org/packages/DevExtreme.AspNet.Data/2.0.0-rc1
https://www.npmjs.com/package/devextreme-aspnet-data/v/2.0.0-rc1
